apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpay-remit-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: gpay-remit.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gpay-remit-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gpay-remit-frontend
                port:
                  number: 80
